export const OPERATION_KIND = [
  { label: 'EXPENSE', value: 2 },
  { label: 'INCOME', value: 1 },
];

export const AVAILABLE_ICONS_FOR_CATEGORY = [
  { id: 0, name: 'category' },
  { id: 1, name: 'sort' },
  { id: 2, name: 'home' },
  { id: 3, name: 'request_quote' },
  { id: 4, name: 'grade' },
  { id: 5, name: 'favorite' },
  { id: 6, name: 'pets' },
  { id: 7, name: 'forest' },
  { id: 8, name: 'credit_card' },
  { id: 9, name: 'shopping_cart' },
  { id: 10, name: 'savings' },
  { id: 11, name: 'train' },
  { id: 12, name: 'directions_car' },
  { id: 13, name: 'luggage' },
  { id: 14, name: 'trending_up' },
  { id: 15, name: 'phone_iphone' },
  { id: 16, name: 'computer' },
  { id: 17, name: 'flight' },
  { id: 18, name: 'fitness_center' },
  { id: 19, name: 'shopping_basket' },
  { id: 20, name: 'nightlife' },
  { id: 21, name: 'payments' },
  { id: 22, name: 'account_balance_wallet' },
  { id: 23, name: 'radio_button_unchecked' },
];
